pricesapp/poll/urls.py
from django.urls import path
from . import views


app_name = "poll"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name = "index"),
    # ex: /polls/5/
    path("<int:question_id>/detail/this_page_is_the_shit", views.detail, name = "detail"),
    # ex: /polls/5/results
    path("<int:question_id>/results/", views.results, name = "results"),
    # ex: /polls/5/vote
    path("<int:question_id>/vote/", views.vote, name = "vote"),
]

pricesapp/pricesapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("poll/", include("poll.urls"))
]

pricesapp/poll/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    # id - automatically django create a id
    question_text = models.CharField(max_length=255)
    pub_date = models.DateField("date published")
    
    # return text when is called
    def __str__(self):
        return self.question_text
    
    # return recently data 14 hours after today comparate 2 timezones
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)
    
    # return text when is called
    def __str__(self):
        return self.choice_text

pricesapp/poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Question

# view name index, function based view
def index(request):
    lastest_question_list = Question.objects.all()
    # return HttpResponse("You are in main page")
    return render(request, "poll/index.html", {
        "lastest_question_list":lastest_question_list
    })

def detail(request, question_id):
    # question = Question.objects.get(pk=question_id) - Option 1
    question = get_object_or_404(Question, pk= question_id)
    # return HttpResponse(f"You are looking question # {question_id} ")
    return render(request, "poll/detail.html", {
        "question": question
    })

def results(request, question_id):
    return HttpResponse(f"You are looking results from question # {question_id} ")

def vote(request, question_id):
    return HttpResponse(f"You are voting to question # {question_id} ")

pricesapp/poll/templates/poll/detail.html
<form action="{% url 'poll:vote' question.id %}" method = "post">
    {% csrf_token %} 
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {% if error_message %}
            <p><strong>{{error_message}}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            {% comment %} <li>{{ choice.choice_text}} </li> {% endcomment %}
            <input 
                type="radio"
                name="choice"
                id="choice{{ forloop.counter }}"
                value="{{choice.id}}"
            >
            <label for="choice{{ forloop.counter }}">
                {{choice.choice_text}}
            </label>
            <br>
        {% endfor %}
    </fieldset>
<input type="submit" value="vote">
</form>


<!-- {% comment %} <h1>{{question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text}} </li>
{% endfor %}
</ul> {% endcomment %}
-->

pricesapp/poll/templates/poll/index.html
{% if lastest_question_list %}
   <ul>
    {% for question in lastest_question_list %}
        <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
   </ul> 
{% else %}
   <p>No polls are available.</p>
{% endif %}